cacheFolder: .yarn/cache
checksumBehavior: ignore
enableGlobalCache: false
enableImmutableInstalls: false
nodeLinker: node-modules
supportedArchitectures:
  cpu:
    - current
    - arm64
    - x64
  libc:
    - current
    - glibc
    - musl
  os:
    - current
    - linux
    - darwin
