name: "Node Setup"
description: "Sets up Node, restores cache, installs deps"

runs:
  using: "composite"
  steps:
    - name: Create .env file
      run: mv ./backend/.env.ci ./backend/.env
      shell: bash

    - name: Setup node
      uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
      with:
        node-version: 24.11

    - name: Setup yarn
      run: corepack enable
      shell: bash

    - name: Restore yarn cache
      uses: actions/cache/restore@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
      id: cache-yarn
      with:
        path: |
          ./backend/.yarn/cache
          ./backend/.yarn/install-state.gz
          ./backend/node_modules
        key: yarn-cache-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          yarn-cache-

    - name: Install node modules
      run: cd ./backend && yarn install --immutable --mode=skip-build
      shell: bash