export type SupabaseRequest = {
    id: string;
    created_at: Date;
    date: Date;
    connection_id: string | null;
    connection_channel: string | null;
    connection_name: string | null;
    connection_backend: string | null;
    connection_endpoint: string | null;
    env: string;
    account_id: string | null;
    account_name: string | null;
    action: string | null;
    success: boolean;
    status: number;
    search_keys: unknown[];
    req_body: string | null;
    req_method: string | null;
    req_url: string | null;
    req_headers: string | null;
    res_status: number | null;
    res_headers: string | null;
    res_body: string | null;
    res_duration: number | null;
    res_error: string | null;
    subrequests: string | null;
    fts: unknown;
    product_ids: string[] | null;
    service: string | null;
  };