version: '3.9'

services:
  octo_validator_server:
    container_name: octo_validator_server
    build:
      context: .
      dockerfile: ./ops/docker/node/production/Dockerfile
    ports:
      - ${PORT}:${PORT}
    restart: unless-stopped