name: "Node Setup"
description: "Sets up Node, restores cache, installs deps"

runs:
  using: "composite"
  steps:
    - name: Create .env file
      run: mv .env.ci .env
      shell: bash

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: 22.15.1

    - name: Setup yarn
      run: corepack enable
      shell: bash

    - name: Restore yarn cache
      uses: actions/cache/restore@v4
      id: cache-yarn
      with:
        path: |
          .yarn/cache
          .yarn/install-state.gz
          node_modules
        key: yarn-cache-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          yarn-cache-

    - name: Install node modules
      run: yarn install --immutable --mode=skip-build
      shell: bash