name: Renovate
on:
  # Allows manual/automated ad-hoc trigger
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Override default log level"
        required: false
        default: "info"
        type: string
      overrideSchedule:
        description: "Override all schedules"
        required: false
        default: "false"
        type: string
  # Run a few times through the day to catch up with any decisions made in the issue
  # Run at odd times to avoid overlap with too many other workflows on GitHub Actions
  # note github actions cron is in UTC so this is 7:18am, 12:18pm, 15:18pm in AEST.
  #schedule:
  #  - cron: "18 21,2,5 * * *"
concurrency: renovate
jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v41.0.12
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          RENOVATE_PLATFORM_COMMIT: "true"

          RENOVATE_FORCE: ${{ github.event.inputs.overrideSchedule == 'true' && '{''schedule'':null}' || '' }}
          LOG_LEVEL: ${{ inputs.logLevel || 'info' }}
        with:
          token: ${{ secrets.OCTO_GITHUB_SYNC_TOKEN }}