name: Backend Code Check

on:
  pull_request:
    branches:
      - '!main'
      - '**'
  workflow_dispatch:

env:
  NODE_VERSION: 22.15.1

jobs:
  build:
    name: Build
    defaults:
      run:
        working-directory: ./backend
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup
        uses: ./.github/actions/backend-node-setup

      - name: Build the project
        run: yarn run esbuild

  check-types:
    name: Check Types
    defaults:
      run:
        working-directory: ./backend
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup
        uses: ./.github/actions/backend-node-setup

      - name: Do dry build
        run: yarn run build:dry

  check-code-quality:
    name: Check code quality
    defaults:
      run:
        working-directory: ./backend
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: 2.1.4
      
      - name: Run Biome
        run: biome ci .

  run-common-tests:
    name: Run common tests
    defaults:
      run:
        working-directory: ./backend
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup
        uses: ./.github/actions/backend-node-setup

      - name: Run Vitest
        run: yarn test